---
- name: UPDATE NTP SERVER 
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: UPDATE THE NTP SERVER
      ios_config:
        commands:
          - ntp server 10.1.1.1
